<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roboparty_head</name>
  <version>0.1.0</version>
  <description>roboparty head controller package (2-axis LRO: 1=yaw left/right, 2=pitch up/down)</description>
  <maintainer email="1984715306@qq.com">changchuanyong</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>roboparty_motors</build_depend>

  <exec_depend>roboparty_motors</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
